// presentation/frontend-react/src/features/bidding/RestBidding.tsx
import { useState } from 'react';
import type { FormEvent } from 'react';

import { bffApiClient } from '../../core/api/bffApiClient';
import type { RestBiddingResponse, System } from '../../core/api/bffApiClient';

interface RestBiddingForm {
  northHand: string;
  southHand: string;
  bidding: string;
  system: System;
}

const initialForm: RestBiddingForm = {
  northHand: '',
  southHand: '',
  bidding: '',
  system: 'POLISH_CLUB'
};

export function RestBidding() {
  const [form, setForm] = useState<RestBiddingForm>(initialForm);
  const [touched, setTouched] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<RestBiddingResponse | null>(null);

  const northValid = form.northHand.trim().length > 0;
  const southValid = form.southHand.trim().length > 0;
  const formValid = northValid && southValid;

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setTouched(true);

    if (!formValid) {
      return;
    }

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await bffApiClient.recommendBidding(form);
      setResult(response);
    } catch {
      setError('Request failed');
    } finally {
      setLoading(false);
    }
  }

  function reset() {
    setForm(initialForm);
    setTouched(false);
    setError(null);
    setResult(null);
  }

  return (
    <section className="section-card">
      <form className="form" onSubmit={submit}>
        <article className="bid-card">
          <header className="card-header">
            <h1>Full bidding calculator</h1>
            <p>Enter hands and bidding sequence</p>
          </header>

          <div className="form-layout">
            <label className="field">
              <span>North</span>
              <textarea
                rows={4}
                value={form.northHand}
                onBlur={() => setTouched(true)}
                onChange={(event) => setForm({ ...form, northHand: event.target.value })}
              />
              {touched && !northValid ? <small className="field-error">North hand is required</small> : null}
            </label>

            <label className="field">
              <span>South</span>
              <textarea
                rows={4}
                value={form.southHand}
                onBlur={() => setTouched(true)}
                onChange={(event) => setForm({ ...form, southHand: event.target.value })}
              />
              {touched && !southValid ? <small className="field-error">South hand is required</small> : null}
            </label>

            <label className="field">
              <span>Bidding</span>
              <textarea
                rows={4}
                value={form.bidding}
                onChange={(event) => setForm({ ...form, bidding: event.target.value })}
              />
            </label>

            <label className="field">
              <span>System</span>
              <select
                value={form.system}
                onChange={(event) => setForm({ ...form, system: event.target.value as System })}
              >
                <option value="POLISH_CLUB">Polish Club</option>
                <option value="STANDARD_AMERICAN">Standard American</option>
              </select>
            </label>

            {error ? <div className="result-panel error-panel">{error}</div> : null}

            {result ? (
              <details className="result-panel" open>
                <summary>{result.bidding}</summary>
                <p>{result.explanation}</p>
              </details>
            ) : null}
          </div>

          <footer className="card-actions">
            <button className="primary-action" type="submit" disabled={loading || !formValid}>
              {loading ? 'Calculating...' : 'Calculate'}
            </button>
            <button className="secondary-action" type="button" onClick={reset}>
              Reset
            </button>
          </footer>
        </article>
      </form>
    </section>
  );
}

// presentation/frontend-angular/src/app/features/bidding/rest-bidding/rest-bidding.component.ts

import { Component, computed, inject, signal } from '@angular/core';
import { ReactiveFormsModule, FormControl, FormGroup } from '@angular/forms';
import { DestroyRef } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

import { FeaturePanelComponent } from '@shared/ui/feature-panel/feature-panel.component';
import { RestBiddingService } from './rest-bidding.service';
import { RestBiddingResponse } from '@core/api/bff/dto/rest-bidding.dto';
import { System } from './rest-bidding.model';

@Component({
    selector: 'app-rest-bidding',
    imports: [ReactiveFormsModule, FeaturePanelComponent],
    providers: [RestBiddingService],
    templateUrl: './rest-bidding.component.html'
})
export class RestBiddingComponent {

  private readonly service = inject(RestBiddingService);
  private readonly destroyRef = inject(DestroyRef);

  // =========================
  // FORM
  // =========================
  readonly form = new FormGroup({
    northHand: new FormControl<string>('', { nonNullable: true }),
    southHand: new FormControl<string>('', { nonNullable: true }),
    bidding: new FormControl<string>('', { nonNullable: true }),
    system: new FormControl<System>('POLISH_CLUB', { nonNullable: true }),
  });

  // =========================
  // UI STATE
  // =========================
  readonly loading = signal(false);
  readonly error = signal<string | null>(null);
  readonly result = signal<RestBiddingResponse | null>(null);

  // =========================
  // VIEW MODEL
  // =========================
  readonly vm = computed(() => ({
    loading: this.loading(),
    error: this.error(),
    result: this.result(),
    formValid: this.form.valid,
  }));

  // =========================
  // ACTIONS
  // =========================
  submit(): void {
    if (this.form.invalid) return;

    this.loading.set(true);
    this.error.set(null);
    this.result.set(null);

    this.service.recommendBidding(this.form.getRawValue())
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (res) => {
          this.result.set(res);
          this.loading.set(false);
        },
        error: () => {
          this.error.set('Request failed');
          this.loading.set(false);
        }
      });
  }

  reset(): void {
    this.form.reset({
      northHand: '',
      southHand: '',
      bidding: '',
      system: 'POLISH_CLUB',
    });

    this.result.set(null);
    this.error.set(null);
  }
}

<mat-card class="section-card">
  <form class="form" [formGroup]="form" (ngSubmit)="submit()">

    <mat-card class="bid-card">

      <!-- HEADER -->
      <mat-card-header>
        <mat-card-title>Full bidding calculator</mat-card-title>
        <mat-card-subtitle>Enter hands and bidding sequence</mat-card-subtitle>
      </mat-card-header>

      <!-- CONTENT -->
      <mat-card-content class="form-layout">

        <!-- NORTH -->
        <mat-form-field appearance="outline" class="full-width">
          <mat-label>North</mat-label>

          <textarea matInput rows="4" formControlName="northHand"></textarea>

          @if (form.controls.northHand.touched && form.controls.northHand.hasError('required')) {
          <mat-error>North hand is required</mat-error>
          }
        </mat-form-field>

        <!-- SOUTH -->
        <mat-form-field appearance="outline" class="full-width">
          <mat-label>South</mat-label>

          <textarea matInput rows="4" formControlName="southHand"></textarea>

          @if (form.controls.southHand.touched && form.controls.southHand.hasError('required')) {
          <mat-error>South hand is required</mat-error>
          }
        </mat-form-field>

        <!-- BIDDING -->
        <mat-form-field appearance="outline" class="full-width">
          <mat-label>Bidding</mat-label>

          <textarea matInput rows="4" formControlName="bidding"></textarea>
        </mat-form-field>

        <!-- SYSTEM -->
        <mat-form-field appearance="outline" class="full-width">
          <mat-label>System</mat-label>

          <mat-select formControlName="system">
            <mat-option value="POLISH_CLUB">Polish Club</mat-option>
            <mat-option value="STANDARD_AMERICAN">Standard American</mat-option>
          </mat-select>
        </mat-form-field>

        <!-- RESULT -->
        @if (result(); as r) {
        <mat-expansion-panel expanded>

          <mat-expansion-panel-header>
            <mat-panel-title>
              {{ r.bidding }}
            </mat-panel-title>
          </mat-expansion-panel-header>

          <p>{{ r.explanation }}</p>

        </mat-expansion-panel>
        }

      </mat-card-content>

      <!-- ACTIONS -->
      <mat-card-actions>

        <button mat-raised-button color="primary" type="submit" [disabled]="loading() || form.invalid">
          {{ loading() ? 'Calculating...' : 'Calculate' }}
        </button>

        <button mat-button type="button" (click)="reset()">
          Reset
        </button>

      </mat-card-actions>

    </mat-card>

  </form>
</mat-card>
